basePackages:
  - base
  - base-devel
  - bash
  - bash-completion
  - linux
  - linux-firmware
  - mkinitcpio
  - lvm2
  - grub
  - vim
  - sudo
  - networkmanager
  - openssh
  - cryptsetup
  - device-mapper
  - diffutils
  - dosfstools
  - e2fsprogs
  - efibootmgr
  - exfatprogs
  - f2fs-tools
  - inetutils
  - iptables-nft
  - jfsutils
  - less
  - logrotate
  - lsb-release
  - man-db
  - man-pages
  - mdadm
  - micro
  - nano
  - netctl
  - ntfs-3g
  - os-prober
  - perl
  - python
  - sudo
  - sysfsutils
  - systemd-sysvcompat
  - texinfo
  - usbutils
  - which
  - xfsprogs
  - cockpit
  - cockpit-files
  - cockpit-pacman
  - 389-ds-base
  - python-psutil
  - firewalld
  - bind
  - plymouth
  - rust
  - ncurses
  - dialog
  - trash-cli
  - safe-rm
