i18n:
     name: "Installing cockpit-pacman in jetDS"

dontChroot: true
timeout: 300
script:
    - "cp /var/cache/pacman/pkg/cockpit-pacman-0.3.5-2-x86_64.pkg.tar.zst ${ROOT}/var/cache/pacman/pkg/"
    - command: "arch-chroot ${ROOT} pacman -U --noconfirm /var/cache/pacman/pkg/cockpit-pacman-0.3.5-2-x86_64.pkg.tar.zst"
