# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# shellprocess_initialize_pacman.conf
# generate pacman keyring, mirrorlist and copy them into target system
---

dontChroot: true

script:
 - command: "mount -o remount,size=2G /run/archiso/cowspace"
 - command: "pacman -Sy --noconfirm archlinux-keyring"
   timeout: 1200
 - command: "chmod +x /etc/calamares/scripts/*"
 - command: "bash /etc/calamares/scripts/update-mirrorlist"
   timeout: 1200
 - "cp /etc/pacman.d/mirrorlist ${ROOT}/etc/pacman.d/"
 - "cp -a /etc/pacman.d/gnupg ${ROOT}/etc/pacman.d/"
 - "cp /etc/resolv.conf ${ROOT}/etc/"

i18n:
 name: "Initializing..."
