# /etc/calamares/modules/shellprocess_jetds_welcome.conf
---
dontChroot: true
timeout: 30
script:
    - /usr/bin/install -Dm755 /usr/share/jetds/jetds-welcome ${ROOT}/usr/local/bin/jetds-welcome
    - /usr/bin/install -Dm644 /usr/share/jetds/jetds-welcome.service ${ROOT}/etc/systemd/system/jetds-welcome.service
    - /usr/bin/arch-chroot ${ROOT} /usr/bin/systemctl enable jetds-welcome.service
    - cp /usr/share/jetds/idle_timeout.sh ${ROOT}/etc/profile.d/ # Contains a timeout
    - chmod +x ${ROOT}/etc/profile.d/idle_timeout.sh
    - cp /etc/bash.bashrc ${ROOT}/etc/ # Contains the aliases for rm, cp, and mv commands; does not stop glob expansion (*) though.
    - cp /etc/safe-rm.conf ${ROOT}/etc/
    - chmod +x /usr/local/bin/*
    - sed -i "s/#ClientAliveInterval 0/ClientAliveInterval 600/" ${ROOT}/etc/ssh/sshd_config

i18n:
  name: "Performing Post-Installation"
