# /etc/calamares/modules/shellprocess_jetds_welcome.conf
---
dontChroot: true
timeout: 30
script:
    - cp -r /usr/share/plymouth/themes/jetDS ${ROOT}/usr/share/plymouth/themes/
    - cp /etc/plymouth/plymouthd.conf ${ROOT}/etc/plymouth/
    - "cp -r /usr/share/jetds/grub.d ${ROOT}/etc/" # Not to do with Plymouth but for GRUB.

i18n:
 name: "Perforning a splash screen for booting up jetDS..."
